package recipeParser.ingrControllers;

public enum SubstitutionType {
	CHINESE_TO_INDIAN,
	INDIAN_TO_CHINESE,
	CHINESE_TO_ITALIAN,
	ITALIAN_TO_CHINESE,
	EASTERNEUROPEAN_TO_CHINESE,
	CHINESE_TO_EASTERNEUROPEAN,
	EASTERNEUROPEAN_TO_ITALIAN,
	ITALIAN_TO_EASTERNEUROPEAN,
	EASTERNEUROPEAN_TO_INDIAN,
	INDIAN_TO_EASTERNEUROPEAN,
	INDIAN_TO_ITALIAN,
	ITALIAN_TO_INDIAN
}
